import{CalendarDays,Clock3,MapPin,Send,UserRound,Users}from'lucide-react';
export function WorkforceHealthScore(){return <div className="health card"><h4>Workforce Health Score</h4><div className="score-row"><div className="score"><strong>82</strong><small>/100</small></div><div><b>GOOD</b><p>Workforce is performing well.<br/>3 items need attention.</p></div></div></div>}
export function AskShadyChat(){return <div className="shady card"><div className="visual-title"><span className="avatar">AS</span><div><b>Ask Shady</b><small>Your AI workforce assistant</small></div></div><div className="ask-input">Ask a question about your workforce… <Send size={14}/></div><div className="prompt-row"><span>Who hasn’t arrived?</span><span>Who is working tonight?</span><span>Show me overtime</span></div></div>}
export function DepartmentStatus(){const rows=[['Emergency Unit','24 / 28','4 short'],['Medical Ward','18 / 20','Good'],['Theatre','12 / 12','Full'],['OPD','16 / 18','2 short']];return <div className="department card"><h4>Live Workforce</h4>{rows.map((r,i)=><div className="department-row" key={r[0]}><span className="dept-name"><UserRound size={13}/>{r[0]}</span><b>{r[1]}</b><em className={i===0||i===3?'warn':'good'}>{r[2]}</em></div>)}</div>}
export function GeofenceMapMockup(){return <div className="map card"><div className="map-head"><b>Workforce Location</b><span><i className="live-dot"/> Live</span></div><div className="map-canvas"><span className="road r1"/><span className="road r2"/><span className="road r3"/><div className="zone"><MapPin size={19}/><strong>Main Hospital</strong><small>Authorized Zone</small></div>{[[18,34],[29,70],[72,20],[80,63],[58,79]].map((p,i)=><i key={i} className={'map-dot d'+i} style={{left:p[0]+'%',top:p[1]+'%'}}/>)}</div><div className="map-key"><span><i className="green"/>On site 12</span><span><i className="red-bg"/>Outside zone 2</span></div></div>}
export function ExecutiveDashboard(){return <div className="device"><aside className="device-side"><strong>IRRIVO</strong>{['Dashboard','Employees','Rosters','Attendance','Analytics','Reports','Ask Shady','Organization','Settings'].map((x,i)=><span key={x} className={i===0?'active':''}>{i===0?<ChartGlyph/>:<i/>}{x}</span>)}</aside><div className="device-main"><div className="welcome"><div><h3>Good morning, Alex</h3><p>Here’s what’s happening across your workforce today.</p></div><span>Thu, 14 Nov 2024</span></div><div className="metric-grid">{[[CalendarDays,'128','Scheduled today'],[UserRound,'94','Currently on duty'],[Clock3,'7','Late'],[Users,'4','Not arrived']].map(([Icon,num,label])=><div className="metric" key={String(label)}><Icon size={18}/><b>{String(num)}</b><small>{String(label)}</small></div>)}</div><div className="visual-grid"><WorkforceHealthScore/><AskShadyChat/><DepartmentStatus/><GeofenceMapMockup/></div></div></div>}
function ChartGlyph(){return <span className="chart-glyph"><i/><i/><i/></span>}
export function LiveWorkforcePanel(){const items=[['Who is working now?','94 on duty','↑ 12% from yesterday','green'],['Who is late?','7 employees','↑ 2% from yesterday','orange'],["Who hasn’t arrived?",'4 employees','↓ 50% from yesterday','red'],['Which department needs attention?','Emergency Unit','4 short today','blue'],['Who is working next?','28 employees','Next shift starts at 14:00','cyan'],['Who is outside the work location?','2 employees','Outside authorized zone','red']];return <div className="live-panel">{items.map((x,i)=><div key={x[0]}><span className={'live-icon '+x[3]}>{i===1?<Clock3/>:i===4?<CalendarDays/>:i===5?<MapPin/>:<Users/>}</span><section><b>{x[0]}</b><strong>{x[1]}</strong><small>{x[2]}</small></section></div>)}</div>}
export function RosterGrid(){return <div className="roster card"><div className="roster-head"><b>Weekly roster</b><span>Coverage optimized</span></div><div className="roster-table">{['Morning','Afternoon','Night','Custom'].map((shift,i)=><div key={shift}><b>{shift}</b>{Array.from({length:5},(_,d)=><span className={(d+i)%4===0?'empty':''} key={d}>{(d+i)%4===0?'Open':`${6+((d+i)%4)} staff`}</span>)}</div>)}</div></div>}
export function AnalyticsChart(){return <div className="analytics card"><div className="analytics-head"><div><small>Attendance overview</small><strong>96.2%</strong></div><span>Last 30 days</span></div><div className="bars">{[62,78,67,90,74,84,92,72,86,96,79,88].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="chart-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></div>}
